services:
  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_URL_WITH_SCHEMA: ${DATABASE_URL_WITH_SCHEMA}
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: portal-api